name: Lint and test

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      -
        name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2
      -
        name: Rust format
        run: mise run fmt-check
      -
        name: Clippy
        run: mise run clippy
      -
        name: ShellCheck
        run: mise run shellcheck
      -
        name: Dependency audit
        run: mise run audit
      -
        name: Dependency policy
        run: mise run deny
      -
        name: Markdownlint
        run: mise run markdownlint
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      -
        name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2
      -
        name: Google Cloud image
        run: docker compose build googlecloud
      -
        name: Rust tests
        run: mise run test
